#!/usr/bin/expect
set datadir [lindex $argv 0]
# 6 num at least wanted
set wallet_password [lindex $argv 1]
# 10 characters at least wanted
set account_password 1234567890

set timeout 5
spawn ./bin/geth bls account new --datadir $datadir
expect "*assword:*"
send "$wallet_password\r"
expect "*assword:*"
send "$wallet_password\r"
expect "*assword:*"
send "$account_password\r"
expect "*assword:*"
send "$account_password\r"
expect EOF