global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090
# node exporters, the targer node_exporter service must started
- job_name: bsc-validator
  metrics_path: '/debug/metrics/prometheus'
  static_configs:
  - targets: ['host.docker.internal:6060', 'host.docker.internal:6061', 'host.docker.internal:6062', 'host.docker.internal:6063', 'host.docker.internal:6064', 'host.docker.internal:6065']
- job_name: bsc-fullnode
  metrics_path: '/debug/metrics/prometheus'
  static_configs:
  - targets: ['host.docker.internal:6100', 'host.docker.internal:6101']
